# Generated by Django 5.2 on 2025-05-27 21:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelQueryDomainJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(help_text='Foreign key linking to a SlasherQuery.', max_length=64)),
                ('domain_id', models.CharField(help_text='Foreign key linking to a SlasherDomain.', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ModelQueryHashJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(help_text='Foreign key linking to a SlasherQuery.', max_length=64)),
                ('hash_id', models.CharField(help_text='Foreign key linking to a SlasherHash.', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ModelQueryIPJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.CharField(help_text='Foreign key linking to a SlasherQuery.', max_length=64)),
                ('ip_id', models.CharField(help_text='Foreign key linking to a SlasherIP.', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ModelSlasherDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vt_status', models.CharField(choices=[('completed', 'Completed'), ('error', 'Error'), ('pending', 'Pending'), ('unknown', 'Unknown')], default='pending', help_text='The current status of the VirusTotal query.', max_length=9)),
                ('vt_meta', models.TextField(help_text='Metadata returned by VirusTotal after query execution.')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slasher_domain', models.CharField(help_text='The domain name provided by the user.', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelSlasherHash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vt_status', models.CharField(choices=[('completed', 'Completed'), ('error', 'Error'), ('pending', 'Pending'), ('unknown', 'Unknown')], default='pending', help_text='The current status of the VirusTotal query.', max_length=9)),
                ('vt_meta', models.TextField(help_text='Metadata returned by VirusTotal after query execution.')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slasher_hash', models.CharField(help_text='The hash value provided by the user for analysis.', max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelSlasherIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vt_status', models.CharField(choices=[('completed', 'Completed'), ('error', 'Error'), ('pending', 'Pending'), ('unknown', 'Unknown')], default='pending', help_text='The current status of the VirusTotal query.', max_length=9)),
                ('vt_meta', models.TextField(help_text='Metadata returned by VirusTotal after query execution.')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('slasher_ip', models.CharField(help_text='The IP address provided by the user (IPv4 or IPv6).', max_length=39)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelSlasherQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('query_status', models.CharField(choices=[('completed', 'Completed'), ('error', 'Error'), ('pending', 'Pending'), ('unknown', 'Unknown')], default='pending', help_text='The current status of the query (e.g., pending, success).', max_length=9)),
                ('query_analyst', models.CharField(help_text='The name of the analyst who initiated the query.', max_length=128)),
                ('query_case_name', models.CharField(help_text='The name of the case linked to this query.', max_length=256)),
                ('query_date', models.DateTimeField(auto_now_add=True, help_text='The date and time when the query was executed. Set automatically.')),
            ],
        ),
    ]
