# Generated by Django 4.2.14 on 2024-09-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slhasherhash',
            old_name='hash_sha256',
            new_name='slhasher_hash',
        ),
    ]
