# Generated by Django 4.2.14 on 2024-09-22 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_slhasherhash_vt_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slhasherhash',
            name='vt_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('success', 'Success'), ('error', 'Error')], default='unknown', max_length=7),
        ),
        migrations.AlterField(
            model_name='slhasherquery',
            name='query_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
