services:
  slasher_backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/usr/src/slasher/backend
    ports:
      - ${SLASHER_API_PORT}:8000
    env_file:
      - ./.env

  slasher_frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/usr/src/slasher/frontend
    ports:
      - ${SLASHER_FRONTEND_PORT}:80